<?php

namespace App\Console\Commands\NetSuite;

use App\Models\NetSuiteCountry;
use App\Models\NetSuiteCurrency;
use App\Models\NetSuiteMSIC;
use App\Services\GoogleSheetsService;
use App\Services\KissflowService;
use App\Services\NetSuiteRestService;
use App\Services\NetSuiteService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class PushVendorsFromSheets extends Command
{
    protected $signature = 'netsuite:push-vendors-from-sheets {--force : Force push even if vendor already exists} {--spreadsheet-id= : Override spreadsheet ID from env} {--debug : Show detailed debug information} {--rest : Use REST API instead of SOAP (not recommended - has validation issues)}';
    protected $description = 'Push vendors from Google Sheets to NetSuite (uses SOAP API by default)';

    public function handle(GoogleSheetsService $sheetsService, NetSuiteRestService $netSuiteRestService, NetSuiteService $netSuiteService, KissflowService $kissflowService)
    {
        $this->info('Starting vendor push from Google Sheets to NetSuite...');

        // Get spreadsheet ID from option or env
        $spreadsheetId = $this->option('spreadsheet-id') ?? config('google-sheets.vendors_spreadsheet_id');

        if (empty($spreadsheetId)) {
            $this->error('No spreadsheet ID provided. Set VENDORS_SPREADSHEET_ID in .env or use --spreadsheet-id option');
            return Command::FAILURE;
        }

        $environment = config('netsuite.environment', 'sandbox');
        $isSandbox = $environment === 'sandbox';
        $useREST = $this->option('rest');
        $apiType = $useREST ? 'REST' : 'SOAP';
        
        $this->info("Using spreadsheet ID: {$spreadsheetId}");
        $this->info("NetSuite Environment: {$environment}");
        $this->info("API Mode: {$apiType}" . ($useREST ? ' ⚠️  (may have validation issues)' : ' ✓ (recommended)'));
        $this->newLine();

        try {
            // Read Sheet1
            $this->info('Reading Sheet1...');
            $rows = $sheetsService->readSheet('Sheet1', $spreadsheetId);

            if (empty($rows) || count($rows) < 2) {
                $this->warn('No vendor data found in Sheet1 (need at least header + 1 row)');
                return Command::SUCCESS;
            }

            // Get headers (first row)
            $headers = array_map('trim', $rows[0]);
            $headerMap = array_flip($headers);

            // Debug: Show all column headers
            $this->info('Sheet1 columns found (' . count($headers) . ' total):');
            foreach ($headers as $index => $header) {
                $this->line("  [{$index}] => '{$header}'");
            }
            $this->newLine();

            // Show sample data if debug mode
            if ($this->option('debug')) {
                $this->info('First 3 data rows (raw):');
                for ($i = 1; $i <= min(3, count($rows) - 1); $i++) {
                    $this->line("Row {$i}: " . json_encode($rows[$i]));
                }
                $this->newLine();
            }

            // Validate required headers
            $requiredHeaders = ['Supplier_Name'];
            foreach ($requiredHeaders as $header) {
                if (!isset($headerMap[$header])) {
                    $this->error("Required header '{$header}' not found in Sheet1");
                    return Command::FAILURE;
                }
            }

            // Optional but recommended: Code header
            if (!isset($headerMap['Code'])) {
                $this->warn("Note: 'Code' column not found. Vendor entity IDs will be auto-generated by NetSuite.");
                $this->newLine();
            }

            $syncedRows = [];
            $syncedRowIndices = []; // Track row indices for deletion
            $errorRows = [];
            $skippedCount = 0;
            $alreadyExistsCount = 0;
            $vendorsForKissflow = []; // Track vendors for Kissflow batch push

            // Process each vendor
            $dataRows = array_slice($rows, 1);
            $totalRows = count($dataRows);
            $progressBar = $this->output->createProgressBar($totalRows);
            $progressBar->start();

            foreach ($dataRows as $index => $row) {
                // Calculate sheet row number (index + 2: 0-based array index + 1 for header + 1 for 1-based sheet)
                $sheetRowNumber = $index + 2;

                // Debug: Show first few rows to understand the data
                if ($this->option('debug') && $index < 3) {
                    $this->newLine();
                    $this->line("Debug - Row {$sheetRowNumber}:");
                    $this->line("  Row array length: " . count($row));
                    $this->line("  Supplier_Name column index: " . ($headerMap['Supplier_Name'] ?? 'NOT FOUND'));
                    if (isset($headerMap['Supplier_Name']) && isset($row[$headerMap['Supplier_Name']])) {
                        $this->line("  Supplier_Name value: '" . $row[$headerMap['Supplier_Name']] . "'");
                    }
                    if (isset($headerMap['Code'])) {
                        $this->line("  Code column index: " . $headerMap['Code']);
                        if (isset($row[$headerMap['Code']])) {
                            $this->line("  Code value: '" . $row[$headerMap['Code']] . "'");
                        } else {
                            $this->line("  Code value: NOT SET");
                        }
                    }
                    $this->line("  Full row data: " . json_encode($row));
                }

                if (empty($row)) {
                    $this->newLine();
                    $this->warn("  Row {$sheetRowNumber}: Empty row array, skipping");
                    $skippedCount++;
                    $progressBar->advance();
                    continue;
                }

                // Check for Supplier_Name (required)
                if (!isset($row[$headerMap['Supplier_Name']])) {
                    $this->newLine();
                    $this->warn("  Row {$sheetRowNumber}: Supplier_Name column not found, skipping");
                    $skippedCount++;
                    $progressBar->advance();
                    continue;
                }

                $supplierName = trim($row[$headerMap['Supplier_Name']]);
                if (empty($supplierName)) {
                    $this->newLine();
                    $this->warn("  Row {$sheetRowNumber}: Supplier_Name is empty, skipping");
                    $skippedCount++;
                    $progressBar->advance();
                    continue;
                }

                // Get vendor code if provided (optional)
                $vendorCode = null;
                if (isset($headerMap['Code']) && isset($row[$headerMap['Code']])) {
                    $vendorCode = trim($row[$headerMap['Code']]);
                    if (empty($vendorCode)) {
                        $vendorCode = null; // Treat empty as not provided
                    }
                }

                // Use supplier name or code for identification
                $vendorIdentifier = $vendorCode ?? $supplierName;

                // Check if vendor already exists (only if Code is provided)
                if (!$this->option('force') && $vendorCode) {
                    $this->newLine();
                    $this->line("  Checking if vendor '{$vendorCode}' exists in NetSuite ({$environment})...");

                    if ($netSuiteRestService->vendorExistsByEntityId($vendorCode)) {
                        $this->warn("  ✗ Vendor '{$vendorCode}' already exists in NetSuite. Skipping.");

                        $timestamp = $this->getTimestampFromRow($row, $headerMap);

                        $errorRow = [
                            $timestamp,
                            $vendorCode,
                            "Vendor already exists in NetSuite ({$environment})",
                            '',
                            $vendorCode ?? '',
                            $supplierName,
                            $row[$headerMap['Email_1'] ?? 'Email'] ?? '',
                            $row[$headerMap['Phone'] ?? 0] ?? '',
                        ];
                        $errorRows[] = $errorRow;
                        $alreadyExistsCount++;
                        $progressBar->advance();
                        continue;
                    } else {
                        $this->line("  ✓ Vendor '{$vendorCode}' not found, proceeding with creation...");
                    }
                } else if (!$this->option('force') && !$vendorCode) {
                    $this->newLine();
                    $this->line("  No vendor code provided - NetSuite will auto-generate entity ID");
                } else {
                    $this->newLine();
                    $this->warn("  Force mode: Creating vendor {$vendorIdentifier}");
                }

                // Debug: Log that we're processing this vendor
                $this->newLine();
                $this->line("Processing vendor: {$vendorIdentifier}");

                try {
                    // Build vendor data
                    $vendorData = [
                        'company_name' => $supplierName,
                    ];

                    // Only set entity_id if Code is provided
                    if ($vendorCode) {
                        $vendorData['entity_id'] = $vendorCode;
                    }

                    // Email (try Email_1 first, fallback to Email)
                    $emailColumn = isset($headerMap['Email_1']) ? 'Email_1' : (isset($headerMap['Email']) ? 'Email' : null);
                    if ($emailColumn && isset($row[$headerMap[$emailColumn]])) {
                        $vendorData['email'] = trim($row[$headerMap[$emailColumn]]);
                    }

                    // Phone
                    if (isset($headerMap['Phone']) && isset($row[$headerMap['Phone']])) {
                        $vendorData['phone'] = trim($row[$headerMap['Phone']]);
                    }

                    // Is Active (convert to is_inactive - inverse)
                    if (isset($headerMap['Is_Active']) && isset($row[$headerMap['Is_Active']])) {
                        $isActive = strtolower(trim($row[$headerMap['Is_Active']]));
                        $vendorData['is_inactive'] = !in_array($isActive, ['yes', 'true', '1', 'active']);
                    }

                    // Address fields
                    if (isset($headerMap['Address_1']) && isset($row[$headerMap['Address_1']])) {
                        $vendorData['address_1'] = trim($row[$headerMap['Address_1']]);
                    }
                    if (isset($headerMap['Address_2']) && isset($row[$headerMap['Address_2']])) {
                        $vendorData['address_2'] = trim($row[$headerMap['Address_2']]);
                    }
                    if (isset($headerMap['City']) && isset($row[$headerMap['City']])) {
                        $vendorData['city'] = trim($row[$headerMap['City']]);
                    }
                    if (isset($headerMap['State']) && isset($row[$headerMap['State']])) {
                        $vendorData['state'] = trim($row[$headerMap['State']]);
                    }
                    if (isset($headerMap['Country']) && isset($row[$headerMap['Country']])) {
                        $countryInput = trim($row[$headerMap['Country']]);
                        if (!empty($countryInput)) {
                            $this->line("  Looking up Country: {$countryInput}");
                            $country = NetSuiteCountry::findByIdentifier($countryInput, $isSandbox);

                            if ($country) {
                                $vendorData['country'] = $country->country_code;
                                $this->line("  ✓ Country found: {$country->name} ({$country->country_code})");
                            } else {
                                $this->warn("  ⚠ Country '{$countryInput}' not found in database. Run 'php artisan netsuite:sync-countries' first.");
                                // Fallback to old normalization method
                                $vendorData['country'] = $this->normalizeCountryCode($countryInput);
                            }
                        }
                    }
                    if (isset($headerMap['Zip']) && isset($row[$headerMap['Zip']])) {
                        $vendorData['zip'] = trim($row[$headerMap['Zip']]);
                    }

                    // Currency - lookup by code
                    if (isset($headerMap['Primary_Currency']) && isset($row[$headerMap['Primary_Currency']])) {
                        $currencyCode = strtoupper(trim($row[$headerMap['Primary_Currency']]));
                        if (!empty($currencyCode)) {
                            $this->line("  Looking up Currency: {$currencyCode}");
                            $currency = NetSuiteCurrency::where('currency_code', $currencyCode)
                                ->where('is_sandbox', $isSandbox)
                                ->first();

                            if ($currency) {
                                $vendorData['currency_id'] = $currency->netsuite_id;
                                $this->line("  ✓ Currency found: {$currency->name} (ID: {$currency->netsuite_id})");
                            } else {
                                $this->warn("  ⚠ Currency '{$currencyCode}' not found in database");
                            }
                        }
                    }

                    // Determine if vendor is Malaysian (needed for TIN field defaults)
                    $countryInput = isset($headerMap['Country']) && isset($row[$headerMap['Country']])
                        ? strtoupper(trim($row[$headerMap['Country']]))
                        : '';
                    $isMalaysian = in_array($countryInput, ['MALAYSIA', 'MY', 'MYS', '_MALAYSIA']);

                    // TIN/E-Invoicing fields - ALL required by NetSuite (custentity_tin_* fields)
                    // Note: NetSuite REST service will use company details as fallbacks if these are not set
                    
                    // TIN No - REQUIRED (custentity_tin_no)
                    // For non-Malaysian: use "EI00000000030" as default
                    // For Malaysian: MUST provide TIN_Number from sheet (no default)
                    if (isset($headerMap['TIN_Number']) && !empty(trim($row[$headerMap['TIN_Number']] ?? ''))) {
                        $vendorData['tin_no'] = trim($row[$headerMap['TIN_Number']]);
                    } else {
                        if ($isMalaysian) {
                            // Malaysian vendors MUST have a TIN number
                            $this->error("  ✗ Malaysian vendor '{$vendorIdentifier}' is missing TIN_Number in sheet. This is REQUIRED for Malaysian vendors.");
                            $this->line("    Please add TIN_Number column to your sheet for Malaysian vendors.");
                            $failedVendors[] = [
                                'supplier_name' => $supplierName,
                                'code' => $code,
                                'reason' => 'Missing TIN_Number (required for Malaysian vendors)'
                            ];
                            continue; // Skip this vendor
                        } else {
                            // Non-Malaysian vendors use default
                            $vendorData['tin_no'] = 'EI00000000030'; // Default for foreign vendors only
                        }
                    }

                    // Registered Name - REQUIRED (custentity_tin_registeredname) - use company name
                    $vendorData['tin_registered_name'] = $supplierName;

                    // SST Register No - REQUIRED (custentity_tin_sstregisterno)
                    if (isset($headerMap['SST_Number']) && !empty(trim($row[$headerMap['SST_Number']] ?? ''))) {
                        $vendorData['tin_sst_register_no'] = trim($row[$headerMap['SST_Number']]);
                    } else {
                        $vendorData['tin_sst_register_no'] = 'NA';
                    }

                    // MSIC Code - REQUIRED (custentity_tin_msic) - reference to custom record
                    // Sheet provides MSIC_Code as string, NetSuite expects record ID
                    // Lookup from database or default to "00000 : NOT APPLICABLE"
                    $msicCodeFromSheet = isset($headerMap['MSIC_Code']) ? trim($row[$headerMap['MSIC_Code']] ?? '') : '';
                    
                    if (!empty($msicCodeFromSheet)) {
                        // Try to find MSIC in database
                        $msicRecord = NetSuiteMSIC::findByIdentifier($msicCodeFromSheet, !$isSandbox);
                        
                        if ($msicRecord) {
                            $vendorData['tin_msic_id'] = $msicRecord->netsuite_id;
                            $this->line("  ✓ MSIC Code: {$msicCodeFromSheet} → {$msicRecord->ref_name} (ID: {$msicRecord->netsuite_id})");
                        } else {
                            // MSIC code not found in database
                            $this->warn("  ⚠ MSIC Code '{$msicCodeFromSheet}' not found in database, using default (00000 : NOT APPLICABLE)");
                            $this->line("    Run 'php artisan netsuite:sync-msic-codes' to update MSIC database");
                            $vendorData['tin_msic_id'] = '1'; // Default to "00000 : NOT APPLICABLE"
                        }
                    } else {
                        // No MSIC provided, use default
                        $vendorData['tin_msic_id'] = '1'; // Default to "00000 : NOT APPLICABLE"
                    }

                    // Address Line1 - Will use address_1, city, or company name as fallback in REST service
                    // Only set if we have a value from sheet
                    if (isset($headerMap['Address_1']) && !empty(trim($row[$headerMap['Address_1']] ?? ''))) {
                        $vendorData['tin_address_line1'] = trim($row[$headerMap['Address_1']]);
                    }
                    // Don't set default here - let REST service use address_1, city, or company name

                    // City Name - Will use city or country-based default in REST service
                    // Only set if we have a value from sheet
                    if (isset($headerMap['City']) && !empty(trim($row[$headerMap['City']] ?? ''))) {
                        $vendorData['tin_city_name'] = trim($row[$headerMap['City']]);
                    }
                    // Don't set default here - let REST service handle fallbacks

                    // Country Code - REQUIRED (custentity_tin_countrycode) - reference to custom record
                    // Default: ID 158 = "MYS : MALAYSIA" for Malaysian, ID 239 = "USA : UNITED STATES" for others
                    $vendorData['tin_country_code_id'] = $isMalaysian ? '158' : '239';

                    // State Code - REQUIRED (custentity_tin_statecode) - reference to custom record
                    // Default: ID 218 = "17 : Not Applicable"
                    $vendorData['tin_state_code_id'] = '218';

                    // Identification Code - REQUIRED (custentity_tin_id) - string value
                    if (isset($headerMap['Identification_Code']) && !empty(trim($row[$headerMap['Identification_Code']] ?? ''))) {
                        $vendorData['tin_identification_code'] = trim($row[$headerMap['Identification_Code']]);
                    } else {
                        // For non-Malaysian vendors, default to "000000", otherwise use "0"
                        $vendorData['tin_identification_code'] = !$isMalaysian ? '000000' : '0';
                    }

                    // Identification Type - REQUIRED (custentity_tin_idtype) - reference to custom record
                    // Default: ID 2 = "BRN : Business Registration No."
                    $vendorData['tin_id_type_id'] = '2';

                    // Tourism Tax Register - OPTIONAL (custentity_tin_tourismtaxregister)
                    if (isset($headerMap['Tourism_Tax']) && !empty(trim($row[$headerMap['Tourism_Tax']] ?? ''))) {
                        $vendorData['tin_tourism_tax'] = trim($row[$headerMap['Tourism_Tax']]);
                    }

                    $this->line("  TIN/E-Invoicing fields:");
                    $this->line("    TIN No: {$vendorData['tin_no']}");
                    $this->line("    Registered Name: {$vendorData['tin_registered_name']}");
                    $this->line("    SST Register No: {$vendorData['tin_sst_register_no']}");
                    $this->line("    MSIC Code ID: {$vendorData['tin_msic_id']}");
                    $this->line("    Address Line1: " . ($vendorData['tin_address_line1'] ?? '[will use address/city/company name]'));
                    $this->line("    City Name: " . ($vendorData['tin_city_name'] ?? '[will use city or default based on country]'));
                    $this->line("    Country Code ID: {$vendorData['tin_country_code_id']}");
                    $this->line("    State Code ID: {$vendorData['tin_state_code_id']}");
                    $this->line("    Identification Code: {$vendorData['tin_identification_code']}");
                    $this->line("    Identification Type ID: {$vendorData['tin_id_type_id']}");

                    // Create vendor in NetSuite
                    // Default to SOAP (works reliably), unless --rest flag is explicitly set
                    $useREST = $this->option('rest');
                    $apiType = $useREST ? 'REST' : 'SOAP';
                    $this->line("  Creating vendor in NetSuite via {$apiType} API...");
                    
                    if ($useREST) {
                        $this->warn("    ⚠️  Using REST API - may encounter validation issues. Remove --rest flag to use SOAP.");
                        $result = $netSuiteRestService->createVendor($vendorData);
                    } else {
                        $result = $netSuiteService->createVendorWithTINFields($vendorData);
                    }

                    if ($result['success']) {
                        $internalId = $result['internal_id'] ?? null;
                        $entityId = $result['entity_id'] ?? null;

                        $successMsg = "  ✓ Vendor created successfully! Internal ID: {$internalId}";
                        if ($entityId) {
                            $successMsg .= ", Entity ID: {$entityId}";
                        }
                        $this->line($successMsg);

                        // Collect vendor data for Kissflow batch push
                        $vendorsForKissflow[] = [
                            'internal_id' => $internalId,
                            'entity_id' => $entityId,
                            'company_name' => $supplierName,
                            'email' => $vendorData['email'] ?? '',
                            'phone' => $vendorData['phone'] ?? '',
                            'currency' => isset($currency) ? $currency->currency_code : '',
                            'is_inactive' => $vendorData['is_inactive'] ?? false,
                            'address' => $vendorData['address_1'] ?? '',
                            'city' => $vendorData['city'] ?? '',
                            'state' => $vendorData['state'] ?? '',
                            'zip' => $vendorData['zip'] ?? '',
                            'country' => $vendorData['country'] ?? '',
                        ];

                        // Mark as synced - add to synced rows
                        $syncedRow = $row;

                        // Add Internal ID and Entity ID columns if needed
                        if (isset($headerMap['NetSuite_ID'])) {
                            $syncedRow[$headerMap['NetSuite_ID']] = $internalId;
                        }
                        if (isset($headerMap['Code']) && $entityId) {
                            // Update Code column with NetSuite-generated entity ID
                            $syncedRow[$headerMap['Code']] = $entityId;
                        }

                        $syncedRows[] = $syncedRow;
                        $syncedRowIndices[] = $sheetRowNumber;
                    } else {
                        // Get timestamp from sheet or use current time
                        $timestamp = $this->getTimestampFromRow($row, $headerMap);

                        // Build error row for Errors sheet
                        $errorRow = [
                            $timestamp,
                            $vendorIdentifier,
                            $result['error'] ?? 'Unknown error',
                            $result['netsuite_response'] ?? '',
                            $vendorCode ?? '',
                            $supplierName,
                            $row[$emailColumn ? $headerMap[$emailColumn] : 0] ?? '',
                            $row[$headerMap['Phone'] ?? 0] ?? '',
                        ];
                        $errorRows[] = $errorRow;

                        $this->newLine();
                        $this->warn("Failed to create vendor {$vendorIdentifier}: " . ($result['error'] ?? 'Unknown error'));
                    }

                } catch (\Exception $e) {
                    // Get timestamp from sheet or use current time
                    $timestamp = $this->getTimestampFromRow($row, $headerMap);

                    // Build error row for Errors sheet
                    $errorRow = [
                        $timestamp,
                        $vendorIdentifier,
                        $e->getMessage(),
                        '',
                        $vendorCode ?? '',
                        $supplierName,
                        $row[$emailColumn ? $headerMap[$emailColumn] : 0] ?? '',
                        $row[$headerMap['Phone'] ?? 0] ?? '',
                    ];
                    $errorRows[] = $errorRow;

                    $this->newLine();
                    $this->warn("Error processing vendor {$vendorIdentifier}: " . $e->getMessage());
                }

                $progressBar->advance();
            }

            $progressBar->finish();
            $this->newLine(2);

            // Show summary
            $this->info("Summary:");
            $this->info("  Total rows in sheet: " . (count($rows) - 1));
            $this->info("  Skipped (empty/invalid): " . $skippedCount);
            $this->info("  Already exists: " . $alreadyExistsCount);
            $this->info("  Attempted to push: " . (count($rows) - 1 - $skippedCount - $alreadyExistsCount));
            $this->info("  Successfully pushed: " . count($syncedRows));
            $this->info("  Errors: " . count($errorRows));
            $this->newLine();

            // Push successfully created vendors to Kissflow
            if (!empty($vendorsForKissflow)) {
                $this->info("Pushing " . count($vendorsForKissflow) . " vendor(s) to Kissflow dataset...");

                try {
                    $kissflowResult = $kissflowService->pushVendorsBatch($vendorsForKissflow, $isSandbox);

                    if ($kissflowResult['success']) {
                        $this->info("✓ Successfully pushed " . $kissflowResult['count'] . " vendor(s) to Kissflow");
                    } else {
                        $this->warn("⚠ Kissflow push failed: " . ($kissflowResult['error'] ?? 'Unknown error'));
                        $this->warn("  Vendors were still created in NetSuite successfully.");
                    }
                } catch (\Exception $e) {
                    $this->warn("⚠ Kissflow push error: " . $e->getMessage());
                    $this->warn("  Vendors were still created in NetSuite successfully.");
                    Log::error('Kissflow vendor push error', [
                        'error' => $e->getMessage(),
                        'vendor_count' => count($vendorsForKissflow)
                    ]);
                }

                $this->newLine();
            }

            // Move synced rows to 'Synced' sheet
            if (!empty($syncedRows)) {
                $this->info("Moving " . count($syncedRows) . " synced vendor(s) to 'Synced' sheet...");

                $syncedData = [$headers]; // Headers
                foreach ($syncedRows as $row) {
                    $syncedData[] = $row;
                }

                // Append to Synced sheet
                $sheetsService->appendToSheet('Synced', $syncedData, $spreadsheetId);
                $this->info("✓ Synced " . count($syncedRows) . " vendor(s)");

                // Delete synced rows from Sheet1 (delete from bottom to top to avoid index shifting)
                if (!empty($syncedRowIndices)) {
                    $this->info("Removing " . count($syncedRowIndices) . " synced vendor(s) from 'Sheet1'...");

                    rsort($syncedRowIndices);

                    foreach ($syncedRowIndices as $rowIndex) {
                        try {
                            $sheetsService->deleteRows('Sheet1', $rowIndex, 1, $spreadsheetId);
                            usleep(100000); // 0.1 seconds delay
                        } catch (\Exception $e) {
                            $this->warn("  Failed to delete row {$rowIndex} from Sheet1: " . $e->getMessage());
                            Log::error("Failed to delete row {$rowIndex} from Sheet1: " . $e->getMessage());
                        }
                    }

                    $this->info("✓ Removed " . count($syncedRowIndices) . " row(s) from 'Sheet1'");
                }
            }

            // Append errors to 'Errors' sheet
            if (!empty($errorRows)) {
                $this->info("Appending " . count($errorRows) . " error(s) to 'Errors' sheet...");

                $errorHeaders = [
                    'Timestamp',
                    'Vendor_Code',
                    'Error_Message',
                    'NetSuite_Response',
                    'Code',
                    'Supplier_Name',
                    'Email',
                    'Phone'
                ];

                $errorData = [$errorHeaders];
                foreach ($errorRows as $errorRow) {
                    $errorData[] = $errorRow;
                }

                // Append to Errors sheet
                $sheetsService->appendToSheet('Errors', $errorData, $spreadsheetId);
                $this->warn("✗ " . count($errorRows) . " vendor(s) failed - see 'Errors' sheet");
            }

            $this->info("Push completed!");
            return Command::SUCCESS;

        } catch (\Exception $e) {
            $this->error('Error pushing vendors: ' . $e->getMessage());
            Log::error('Vendor push error: ' . $e->getMessage());
            return Command::FAILURE;
        }
    }

    /**
     * Get timestamp from row data if 'Timestamp' header exists, otherwise use current time
     */
    protected function getTimestampFromRow(array $row, array $headerMap): string
    {
        $possibleHeaders = ['Timestamp', 'timestamp', 'TIMESTAMP', 'Time', 'Date', 'DateTime', 'Created'];

        foreach ($possibleHeaders as $headerName) {
            if (isset($headerMap[$headerName])) {
                $timestamp = trim($row[$headerMap[$headerName]] ?? '');
                if (!empty($timestamp)) {
                    return $timestamp;
                }
            }

            foreach ($headerMap as $header => $index) {
                if (strcasecmp($header, $headerName) === 0) {
                    $timestamp = trim($row[$index] ?? '');
                    if (!empty($timestamp)) {
                        return $timestamp;
                    }
                }
            }
        }

        return date('Y-m-d H:i:s');
    }

    /**
     * Normalize country code to NetSuite format
     */
    protected function normalizeCountryCode(string $country): string
    {
        // Map common country names/codes to NetSuite country codes
        $countryMap = [
            'MY' => '_malaysia',
            'MALAYSIA' => '_malaysia',
            'SG' => '_singapore',
            'SINGAPORE' => '_singapore',
            'US' => '_unitedStates',
            'USA' => '_unitedStates',
            'UNITED STATES' => '_unitedStates',
            'UK' => '_unitedKingdom',
            'GB' => '_unitedKingdom',
            'UNITED KINGDOM' => '_unitedKingdom',
            'AU' => '_australia',
            'AUSTRALIA' => '_australia',
            'CN' => '_china',
            'CHINA' => '_china',
            'TH' => '_thailand',
            'THAILAND' => '_thailand',
            'ID' => '_indonesia',
            'INDONESIA' => '_indonesia',
        ];

        $upperCountry = strtoupper(trim($country));
        return $countryMap[$upperCountry] ?? $country;
    }
}
