<?php

namespace App\Console\Commands\NetSuite;

use App\Models\NetSuiteCountry;
use App\Models\NetSuiteCurrency;
use App\Services\GoogleSheetsService;
use App\Services\KissflowService;
use App\Services\NetSuiteRestService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class PushVendorsFromSheets extends Command
{
    protected $signature = 'netsuite:push-vendors-from-sheets {--force : Force push even if vendor already exists} {--spreadsheet-id= : Override spreadsheet ID from env} {--debug : Show detailed debug information}';
    protected $description = 'Push vendors from Google Sheets to NetSuite';

    public function handle(GoogleSheetsService $sheetsService, NetSuiteRestService $netSuiteRestService, KissflowService $kissflowService)
    {
        $this->info('Starting vendor push from Google Sheets to NetSuite...');

        // Get spreadsheet ID from option or env
        $spreadsheetId = $this->option('spreadsheet-id') ?? config('google-sheets.vendors_spreadsheet_id');

        if (empty($spreadsheetId)) {
            $this->error('No spreadsheet ID provided. Set VENDORS_SPREADSHEET_ID in .env or use --spreadsheet-id option');
            return Command::FAILURE;
        }

        $environment = config('netsuite.environment', 'sandbox');
        $isSandbox = $environment === 'sandbox';
        $this->info("Using spreadsheet ID: {$spreadsheetId}");
        $this->info("NetSuite Environment: {$environment}");
        $this->newLine();

        try {
            // Read Sheet1
            $this->info('Reading Sheet1...');
            $rows = $sheetsService->readSheet('Sheet1', $spreadsheetId);

            if (empty($rows) || count($rows) < 2) {
                $this->warn('No vendor data found in Sheet1 (need at least header + 1 row)');
                return Command::SUCCESS;
            }

            // Get headers (first row)
            $headers = array_map('trim', $rows[0]);
            $headerMap = array_flip($headers);

            // Debug: Show all column headers
            $this->info('Sheet1 columns found (' . count($headers) . ' total):');
            foreach ($headers as $index => $header) {
                $this->line("  [{$index}] => '{$header}'");
            }
            $this->newLine();

            // Show sample data if debug mode
            if ($this->option('debug')) {
                $this->info('First 3 data rows (raw):');
                for ($i = 1; $i <= min(3, count($rows) - 1); $i++) {
                    $this->line("Row {$i}: " . json_encode($rows[$i]));
                }
                $this->newLine();
            }

            // Validate required headers
            $requiredHeaders = ['Supplier_Name'];
            foreach ($requiredHeaders as $header) {
                if (!isset($headerMap[$header])) {
                    $this->error("Required header '{$header}' not found in Sheet1");
                    return Command::FAILURE;
                }
            }

            // Optional but recommended: Code header
            if (!isset($headerMap['Code'])) {
                $this->warn("Note: 'Code' column not found. Vendor entity IDs will be auto-generated by NetSuite.");
                $this->newLine();
            }

            $syncedRows = [];
            $syncedRowIndices = []; // Track row indices for deletion
            $errorRows = [];
            $skippedCount = 0;
            $alreadyExistsCount = 0;
            $vendorsForKissflow = []; // Track vendors for Kissflow batch push

            // Process each vendor
            $dataRows = array_slice($rows, 1);
            $totalRows = count($dataRows);
            $progressBar = $this->output->createProgressBar($totalRows);
            $progressBar->start();

            foreach ($dataRows as $index => $row) {
                // Calculate sheet row number (index + 2: 0-based array index + 1 for header + 1 for 1-based sheet)
                $sheetRowNumber = $index + 2;

                // Debug: Show first few rows to understand the data
                if ($this->option('debug') && $index < 3) {
                    $this->newLine();
                    $this->line("Debug - Row {$sheetRowNumber}:");
                    $this->line("  Row array length: " . count($row));
                    $this->line("  Supplier_Name column index: " . ($headerMap['Supplier_Name'] ?? 'NOT FOUND'));
                    if (isset($headerMap['Supplier_Name']) && isset($row[$headerMap['Supplier_Name']])) {
                        $this->line("  Supplier_Name value: '" . $row[$headerMap['Supplier_Name']] . "'");
                    }
                    if (isset($headerMap['Code'])) {
                        $this->line("  Code column index: " . $headerMap['Code']);
                        if (isset($row[$headerMap['Code']])) {
                            $this->line("  Code value: '" . $row[$headerMap['Code']] . "'");
                        } else {
                            $this->line("  Code value: NOT SET");
                        }
                    }
                    $this->line("  Full row data: " . json_encode($row));
                }

                if (empty($row)) {
                    $this->newLine();
                    $this->warn("  Row {$sheetRowNumber}: Empty row array, skipping");
                    $skippedCount++;
                    $progressBar->advance();
                    continue;
                }

                // Check for Supplier_Name (required)
                if (!isset($row[$headerMap['Supplier_Name']])) {
                    $this->newLine();
                    $this->warn("  Row {$sheetRowNumber}: Supplier_Name column not found, skipping");
                    $skippedCount++;
                    $progressBar->advance();
                    continue;
                }

                $supplierName = trim($row[$headerMap['Supplier_Name']]);
                if (empty($supplierName)) {
                    $this->newLine();
                    $this->warn("  Row {$sheetRowNumber}: Supplier_Name is empty, skipping");
                    $skippedCount++;
                    $progressBar->advance();
                    continue;
                }

                // Get vendor code if provided (optional)
                $vendorCode = null;
                if (isset($headerMap['Code']) && isset($row[$headerMap['Code']])) {
                    $vendorCode = trim($row[$headerMap['Code']]);
                    if (empty($vendorCode)) {
                        $vendorCode = null; // Treat empty as not provided
                    }
                }

                // Use supplier name or code for identification
                $vendorIdentifier = $vendorCode ?? $supplierName;

                // Check if vendor already exists (only if Code is provided)
                if (!$this->option('force') && $vendorCode) {
                    $this->newLine();
                    $this->line("  Checking if vendor '{$vendorCode}' exists in NetSuite ({$environment})...");

                    if ($netSuiteRestService->vendorExistsByEntityId($vendorCode)) {
                        $this->warn("  ✗ Vendor '{$vendorCode}' already exists in NetSuite. Skipping.");

                        $timestamp = $this->getTimestampFromRow($row, $headerMap);

                        $errorRow = [
                            $timestamp,
                            $vendorCode,
                            "Vendor already exists in NetSuite ({$environment})",
                            '',
                            $vendorCode ?? '',
                            $supplierName,
                            $row[$headerMap['Email_1'] ?? 'Email'] ?? '',
                            $row[$headerMap['Phone'] ?? 0] ?? '',
                        ];
                        $errorRows[] = $errorRow;
                        $alreadyExistsCount++;
                        $progressBar->advance();
                        continue;
                    } else {
                        $this->line("  ✓ Vendor '{$vendorCode}' not found, proceeding with creation...");
                    }
                } else if (!$this->option('force') && !$vendorCode) {
                    $this->newLine();
                    $this->line("  No vendor code provided - NetSuite will auto-generate entity ID");
                } else {
                    $this->newLine();
                    $this->warn("  Force mode: Creating vendor {$vendorIdentifier}");
                }

                // Debug: Log that we're processing this vendor
                $this->newLine();
                $this->line("Processing vendor: {$vendorIdentifier}");

                try {
                    // Build vendor data
                    $vendorData = [
                        'company_name' => $supplierName,
                    ];

                    // Only set entity_id if Code is provided
                    if ($vendorCode) {
                        $vendorData['entity_id'] = $vendorCode;
                    }

                    // Email (try Email_1 first, fallback to Email)
                    $emailColumn = isset($headerMap['Email_1']) ? 'Email_1' : (isset($headerMap['Email']) ? 'Email' : null);
                    if ($emailColumn && isset($row[$headerMap[$emailColumn]])) {
                        $vendorData['email'] = trim($row[$headerMap[$emailColumn]]);
                    }

                    // Phone
                    if (isset($headerMap['Phone']) && isset($row[$headerMap['Phone']])) {
                        $vendorData['phone'] = trim($row[$headerMap['Phone']]);
                    }

                    // Is Active (convert to is_inactive - inverse)
                    if (isset($headerMap['Is_Active']) && isset($row[$headerMap['Is_Active']])) {
                        $isActive = strtolower(trim($row[$headerMap['Is_Active']]));
                        $vendorData['is_inactive'] = !in_array($isActive, ['yes', 'true', '1', 'active']);
                    }

                    // Address fields
                    if (isset($headerMap['Address_1']) && isset($row[$headerMap['Address_1']])) {
                        $vendorData['address_1'] = trim($row[$headerMap['Address_1']]);
                    }
                    if (isset($headerMap['Address_2']) && isset($row[$headerMap['Address_2']])) {
                        $vendorData['address_2'] = trim($row[$headerMap['Address_2']]);
                    }
                    if (isset($headerMap['City']) && isset($row[$headerMap['City']])) {
                        $vendorData['city'] = trim($row[$headerMap['City']]);
                    }
                    if (isset($headerMap['State']) && isset($row[$headerMap['State']])) {
                        $vendorData['state'] = trim($row[$headerMap['State']]);
                    }
                    if (isset($headerMap['Country']) && isset($row[$headerMap['Country']])) {
                        $countryInput = trim($row[$headerMap['Country']]);
                        if (!empty($countryInput)) {
                            $this->line("  Looking up Country: {$countryInput}");
                            $country = NetSuiteCountry::findByIdentifier($countryInput, $isSandbox);

                            if ($country) {
                                $vendorData['country'] = $country->country_code;
                                $this->line("  ✓ Country found: {$country->name} ({$country->country_code})");
                            } else {
                                $this->warn("  ⚠ Country '{$countryInput}' not found in database. Run 'php artisan netsuite:sync-countries' first.");
                                // Fallback to old normalization method
                                $vendorData['country'] = $this->normalizeCountryCode($countryInput);
                            }
                        }
                    }
                    if (isset($headerMap['Zip']) && isset($row[$headerMap['Zip']])) {
                        $vendorData['zip'] = trim($row[$headerMap['Zip']]);
                    }

                    // Currency - lookup by code
                    if (isset($headerMap['Primary_Currency']) && isset($row[$headerMap['Primary_Currency']])) {
                        $currencyCode = strtoupper(trim($row[$headerMap['Primary_Currency']]));
                        if (!empty($currencyCode)) {
                            $this->line("  Looking up Currency: {$currencyCode}");
                            $currency = NetSuiteCurrency::where('currency_code', $currencyCode)
                                ->where('is_sandbox', $isSandbox)
                                ->first();

                            if ($currency) {
                                $vendorData['currency_id'] = $currency->netsuite_id;
                                $this->line("  ✓ Currency found: {$currency->name} (ID: {$currency->netsuite_id})");
                            } else {
                                $this->warn("  ⚠ Currency '{$currencyCode}' not found in database");
                            }
                        }
                    }

                    // Tax fields
                    if (isset($headerMap['TIN_Number']) && isset($row[$headerMap['TIN_Number']])) {
                        $vendorData['tin_number'] = trim($row[$headerMap['TIN_Number']]);
                    }
                    if (isset($headerMap['SST_Number']) && isset($row[$headerMap['SST_Number']])) {
                        $vendorData['sst_number'] = trim($row[$headerMap['SST_Number']]);
                    }
                    if (isset($headerMap['Tourism_Tax']) && isset($row[$headerMap['Tourism_Tax']])) {
                        $vendorData['tourism_tax'] = trim($row[$headerMap['Tourism_Tax']]);
                    }

                    // TODO: Add lookup logic for Category_of_Suppliers, Vendor_Category, Nature_of_Business, MSIC_Code
                    // These would require lookup tables similar to currencies

                    // E-Invoicing fields - ALL required by NetSuite
                    // Determine if vendor is Malaysian
                    $countryInput = isset($headerMap['Country']) && isset($row[$headerMap['Country']])
                        ? strtoupper(trim($row[$headerMap['Country']]))
                        : '';
                    $isMalaysian = in_array($countryInput, ['MALAYSIA', 'MY', 'MYS', '_MALAYSIA']);

                    // (EInv)TIN No - REQUIRED
                    if (!$isMalaysian) {
                        $vendorData['einv_tin_no'] = 'EI000000000030';
                    } else if (isset($headerMap['TIN_Number']) && !empty($row[$headerMap['TIN_Number']])) {
                        $vendorData['einv_tin_no'] = trim($row[$headerMap['TIN_Number']]);
                    } else {
                        $vendorData['einv_tin_no'] = 'EI000000000030'; // Fallback for MY without TIN
                    }

                    // (EInv)Registered Name - REQUIRED - use company name
                    $vendorData['einv_registered_name'] = $supplierName;

                    // (EInv)SST Register No - REQUIRED - default to "0"
                    if (isset($headerMap['SST_Number']) && !empty($row[$headerMap['SST_Number']])) {
                        $vendorData['einv_sst_register_no'] = trim($row[$headerMap['SST_Number']]);
                    } else {
                        $vendorData['einv_sst_register_no'] = '0';
                    }

                    // (EInv)MSIC Code - REQUIRED - default to "00000"
                    if (isset($headerMap['MSIC_Code']) && !empty($row[$headerMap['MSIC_Code']])) {
                        $vendorData['einv_msic_code'] = trim($row[$headerMap['MSIC_Code']]);
                    } else {
                        $vendorData['einv_msic_code'] = '00000';
                    }

                    // (EInv)Address Line1 - REQUIRED - use from Address_1 field or default
                    if (isset($headerMap['Address_1']) && !empty($row[$headerMap['Address_1']])) {
                        $vendorData['einv_address_line1'] = trim($row[$headerMap['Address_1']]);
                    } else {
                        $vendorData['einv_address_line1'] = '0'; // Default to "0" instead of "-"
                    }

                    // (EInv)City Name - REQUIRED - use from City field or default
                    if (isset($headerMap['City']) && !empty($row[$headerMap['City']])) {
                        $vendorData['einv_city_name'] = trim($row[$headerMap['City']]);
                    } else {
                        // For non-Malaysian vendors, use "Not Applicable", for Malaysian use country name or default
                        if (!$isMalaysian) {
                            $vendorData['einv_city_name'] = 'Not Applicable';
                        } else {
                            $vendorData['einv_city_name'] = 'Kuala Lumpur'; // Default Malaysian city
                        }
                    }

                    // (EInv)Country Code - REQUIRED - use ISO code from Country field
                    $einvCountryCode = null;
                    if (!empty($countryInput)) {
                        $country = NetSuiteCountry::findByIdentifier($countryInput, $isSandbox);
                        if ($country && $country->iso_code_2) {
                            $einvCountryCode = strtoupper($country->iso_code_2);
                        } else if (strlen($countryInput) == 2) {
                            // Fallback to raw input if it looks like an ISO code
                            $einvCountryCode = strtoupper($countryInput);
                        } else {
                            // Try to extract 2-letter code from country name
                            // For non-Malaysian countries, we need the actual ISO code, not MY
                            $einvCountryCode = null; // Will default based on isMalaysian
                        }
                    }
                    // Only default to MY if vendor is actually Malaysian, otherwise use the detected code or leave empty for non-MY
                    if ($isMalaysian) {
                        $vendorData['einv_country_code'] = $einvCountryCode ?? 'MY';
                    } else {
                        // For non-Malaysian vendors, use the detected code or a safe default
                        // If no country code found, we still need to set something - use the country input if it's 2 letters
                        $vendorData['einv_country_code'] = $einvCountryCode ?? (strlen($countryInput) == 2 ? strtoupper($countryInput) : 'US'); // Default to US for non-MY if unclear
                    }

                    // (EInv)State Code - REQUIRED - use from State field or default
                    if (isset($headerMap['State']) && !empty($row[$headerMap['State']])) {
                        $vendorData['einv_state_code'] = trim($row[$headerMap['State']]);
                    } else {
                        $vendorData['einv_state_code'] = '0'; // Default to "0" instead of "-"
                    }

                    // (EInv)Identification Code - REQUIRED
                    if (isset($headerMap['Identification_Code']) && !empty($row[$headerMap['Identification_Code']])) {
                        $vendorData['einv_identification_code'] = trim($row[$headerMap['Identification_Code']]);
                    } else {
                        // For non-Malaysian vendors, default to "000000", otherwise use "0"
                        $vendorData['einv_identification_code'] = !$isMalaysian ? '000000' : '0';
                    }

                    // (EInv)Identification Type - REQUIRED
                    if (isset($headerMap['Identification_Type']) && !empty($row[$headerMap['Identification_Type']])) {
                        $vendorData['einv_identification_type'] = trim($row[$headerMap['Identification_Type']]);
                    } else {
                        // For non-Malaysian vendors, default to "BRN", otherwise use "BRN" as well
                        $vendorData['einv_identification_type'] = 'BRN'; // Default to Business Registration Number
                    }

                    $this->line("  E-Invoicing fields set:");
                    $this->line("    TIN: {$vendorData['einv_tin_no']}");
                    $this->line("    Registered Name: {$vendorData['einv_registered_name']}");
                    $this->line("    SST: {$vendorData['einv_sst_register_no']}");
                    $this->line("    MSIC: {$vendorData['einv_msic_code']}");
                    $this->line("    Address: {$vendorData['einv_address_line1']}");
                    $this->line("    City: {$vendorData['einv_city_name']}");
                    $this->line("    Country: {$vendorData['einv_country_code']}");
                    $this->line("    State: {$vendorData['einv_state_code']}");
                    $this->line("    ID Code: {$vendorData['einv_identification_code']}");
                    $this->line("    ID Type: {$vendorData['einv_identification_type']}");

                    // Create vendor in NetSuite via REST API
                    $this->line("  Creating vendor in NetSuite via REST API...");
                    $result = $netSuiteRestService->createVendor($vendorData);

                    if ($result['success']) {
                        $internalId = $result['internal_id'] ?? null;
                        $entityId = $result['entity_id'] ?? null;

                        $successMsg = "  ✓ Vendor created successfully! Internal ID: {$internalId}";
                        if ($entityId) {
                            $successMsg .= ", Entity ID: {$entityId}";
                        }
                        $this->line($successMsg);

                        // Collect vendor data for Kissflow batch push
                        $vendorsForKissflow[] = [
                            'internal_id' => $internalId,
                            'entity_id' => $entityId,
                            'company_name' => $supplierName,
                            'email' => $vendorData['email'] ?? '',
                            'phone' => $vendorData['phone'] ?? '',
                            'currency' => isset($currency) ? $currency->currency_code : '',
                            'is_inactive' => $vendorData['is_inactive'] ?? false,
                            'address' => $vendorData['address_1'] ?? '',
                            'city' => $vendorData['city'] ?? '',
                            'state' => $vendorData['state'] ?? '',
                            'zip' => $vendorData['zip'] ?? '',
                            'country' => $vendorData['country'] ?? '',
                        ];

                        // Mark as synced - add to synced rows
                        $syncedRow = $row;

                        // Add Internal ID and Entity ID columns if needed
                        if (isset($headerMap['NetSuite_ID'])) {
                            $syncedRow[$headerMap['NetSuite_ID']] = $internalId;
                        }
                        if (isset($headerMap['Code']) && $entityId) {
                            // Update Code column with NetSuite-generated entity ID
                            $syncedRow[$headerMap['Code']] = $entityId;
                        }

                        $syncedRows[] = $syncedRow;
                        $syncedRowIndices[] = $sheetRowNumber;
                    } else {
                        // Get timestamp from sheet or use current time
                        $timestamp = $this->getTimestampFromRow($row, $headerMap);

                        // Build error row for Errors sheet
                        $errorRow = [
                            $timestamp,
                            $vendorIdentifier,
                            $result['error'] ?? 'Unknown error',
                            $result['netsuite_response'] ?? '',
                            $vendorCode ?? '',
                            $supplierName,
                            $row[$emailColumn ? $headerMap[$emailColumn] : 0] ?? '',
                            $row[$headerMap['Phone'] ?? 0] ?? '',
                        ];
                        $errorRows[] = $errorRow;

                        $this->newLine();
                        $this->warn("Failed to create vendor {$vendorIdentifier}: " . ($result['error'] ?? 'Unknown error'));
                    }

                } catch (\Exception $e) {
                    // Get timestamp from sheet or use current time
                    $timestamp = $this->getTimestampFromRow($row, $headerMap);

                    // Build error row for Errors sheet
                    $errorRow = [
                        $timestamp,
                        $vendorIdentifier,
                        $e->getMessage(),
                        '',
                        $vendorCode ?? '',
                        $supplierName,
                        $row[$emailColumn ? $headerMap[$emailColumn] : 0] ?? '',
                        $row[$headerMap['Phone'] ?? 0] ?? '',
                    ];
                    $errorRows[] = $errorRow;

                    $this->newLine();
                    $this->warn("Error processing vendor {$vendorIdentifier}: " . $e->getMessage());
                }

                $progressBar->advance();
            }

            $progressBar->finish();
            $this->newLine(2);

            // Show summary
            $this->info("Summary:");
            $this->info("  Total rows in sheet: " . (count($rows) - 1));
            $this->info("  Skipped (empty/invalid): " . $skippedCount);
            $this->info("  Already exists: " . $alreadyExistsCount);
            $this->info("  Attempted to push: " . (count($rows) - 1 - $skippedCount - $alreadyExistsCount));
            $this->info("  Successfully pushed: " . count($syncedRows));
            $this->info("  Errors: " . count($errorRows));
            $this->newLine();

            // Push successfully created vendors to Kissflow
            if (!empty($vendorsForKissflow)) {
                $this->info("Pushing " . count($vendorsForKissflow) . " vendor(s) to Kissflow dataset...");

                try {
                    $kissflowResult = $kissflowService->pushVendorsBatch($vendorsForKissflow, $isSandbox);

                    if ($kissflowResult['success']) {
                        $this->info("✓ Successfully pushed " . $kissflowResult['count'] . " vendor(s) to Kissflow");
                    } else {
                        $this->warn("⚠ Kissflow push failed: " . ($kissflowResult['error'] ?? 'Unknown error'));
                        $this->warn("  Vendors were still created in NetSuite successfully.");
                    }
                } catch (\Exception $e) {
                    $this->warn("⚠ Kissflow push error: " . $e->getMessage());
                    $this->warn("  Vendors were still created in NetSuite successfully.");
                    Log::error('Kissflow vendor push error', [
                        'error' => $e->getMessage(),
                        'vendor_count' => count($vendorsForKissflow)
                    ]);
                }

                $this->newLine();
            }

            // Move synced rows to 'Synced' sheet
            if (!empty($syncedRows)) {
                $this->info("Moving " . count($syncedRows) . " synced vendor(s) to 'Synced' sheet...");

                $syncedData = [$headers]; // Headers
                foreach ($syncedRows as $row) {
                    $syncedData[] = $row;
                }

                // Append to Synced sheet
                $sheetsService->appendToSheet('Synced', $syncedData, $spreadsheetId);
                $this->info("✓ Synced " . count($syncedRows) . " vendor(s)");

                // Delete synced rows from Sheet1 (delete from bottom to top to avoid index shifting)
                if (!empty($syncedRowIndices)) {
                    $this->info("Removing " . count($syncedRowIndices) . " synced vendor(s) from 'Sheet1'...");

                    rsort($syncedRowIndices);

                    foreach ($syncedRowIndices as $rowIndex) {
                        try {
                            $sheetsService->deleteRows('Sheet1', $rowIndex, 1, $spreadsheetId);
                            usleep(100000); // 0.1 seconds delay
                        } catch (\Exception $e) {
                            $this->warn("  Failed to delete row {$rowIndex} from Sheet1: " . $e->getMessage());
                            Log::error("Failed to delete row {$rowIndex} from Sheet1: " . $e->getMessage());
                        }
                    }

                    $this->info("✓ Removed " . count($syncedRowIndices) . " row(s) from 'Sheet1'");
                }
            }

            // Append errors to 'Errors' sheet
            if (!empty($errorRows)) {
                $this->info("Appending " . count($errorRows) . " error(s) to 'Errors' sheet...");

                $errorHeaders = [
                    'Timestamp',
                    'Vendor_Code',
                    'Error_Message',
                    'NetSuite_Response',
                    'Code',
                    'Supplier_Name',
                    'Email',
                    'Phone'
                ];

                $errorData = [$errorHeaders];
                foreach ($errorRows as $errorRow) {
                    $errorData[] = $errorRow;
                }

                // Append to Errors sheet
                $sheetsService->appendToSheet('Errors', $errorData, $spreadsheetId);
                $this->warn("✗ " . count($errorRows) . " vendor(s) failed - see 'Errors' sheet");
            }

            $this->info("Push completed!");
            return Command::SUCCESS;

        } catch (\Exception $e) {
            $this->error('Error pushing vendors: ' . $e->getMessage());
            Log::error('Vendor push error: ' . $e->getMessage());
            return Command::FAILURE;
        }
    }

    /**
     * Get timestamp from row data if 'Timestamp' header exists, otherwise use current time
     */
    protected function getTimestampFromRow(array $row, array $headerMap): string
    {
        $possibleHeaders = ['Timestamp', 'timestamp', 'TIMESTAMP', 'Time', 'Date', 'DateTime', 'Created'];

        foreach ($possibleHeaders as $headerName) {
            if (isset($headerMap[$headerName])) {
                $timestamp = trim($row[$headerMap[$headerName]] ?? '');
                if (!empty($timestamp)) {
                    return $timestamp;
                }
            }

            foreach ($headerMap as $header => $index) {
                if (strcasecmp($header, $headerName) === 0) {
                    $timestamp = trim($row[$index] ?? '');
                    if (!empty($timestamp)) {
                        return $timestamp;
                    }
                }
            }
        }

        return date('Y-m-d H:i:s');
    }

    /**
     * Normalize country code to NetSuite format
     */
    protected function normalizeCountryCode(string $country): string
    {
        // Map common country names/codes to NetSuite country codes
        $countryMap = [
            'MY' => '_malaysia',
            'MALAYSIA' => '_malaysia',
            'SG' => '_singapore',
            'SINGAPORE' => '_singapore',
            'US' => '_unitedStates',
            'USA' => '_unitedStates',
            'UNITED STATES' => '_unitedStates',
            'UK' => '_unitedKingdom',
            'GB' => '_unitedKingdom',
            'UNITED KINGDOM' => '_unitedKingdom',
            'AU' => '_australia',
            'AUSTRALIA' => '_australia',
            'CN' => '_china',
            'CHINA' => '_china',
            'TH' => '_thailand',
            'THAILAND' => '_thailand',
            'ID' => '_indonesia',
            'INDONESIA' => '_indonesia',
        ];

        $upperCountry = strtoupper(trim($country));
        return $countryMap[$upperCountry] ?? $country;
    }
}
